services:
  - type: web
    name: todo-fastapi-v2
    env: python
    runtime: python-3.11.0
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-postgres-v2
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false

  - type: postgres
    name: todo-postgres-v2
    databaseName: todo_db
    user: todouser
    plan: free
