services:
  - type: web
    name: todo-fastapi
    env: python
    runtime: python-3.11.0
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python test_imports.py && alembic upgrade head
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 1
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: todo-postgres
          property: connectionString
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: false
      - key: APP_HOST
        value: 0.0.0.0
      - key: APP_PORT
        fromDefault: PORT

  - type: postgres
    name: todo-postgres
    databaseName: todo_db
    user: todouser
    plan: free
